name: Restart Codespace Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours on the hour

jobs:
  restart_codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh  # Install GitHub CLI to interact with GitHub API

      - name: Stop Codespace
        run: |
          gh codespace stop --name supreme-spoon-gwxwv6vrx5hwjww
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}

      - name: Wait for a brief moment before restarting
        run: |
          sleep 30  # Optional: wait 30 seconds before restarting

      - name: Restart Codespace
        run: |
          gh codespace start --name supreme-spoon-gwxwv6vrx5hwjww
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
