name: Restart Codespace Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  restart-codespace:
    runs-on: ubuntu-latest
    
    steps:
    - name: Stop Codespace
      run: |
        gh codespace stop --name your-codespace-name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait for 30 seconds
      run: sleep 30

    - name: Restart Codespace
      run: |
        gh codespace start --name your-codespace-name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

