name: Restart Codespace Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  restart-codespace:
    runs-on: ubuntu-latest

  steps:
    - name: Authenticate with GitHub CLI
      run: |
        echo "${{ secrets.GH_CODESPACE_TOKEN }}" | gh auth login --with-token

    - name: Stop Codespace
      run: |
        gh codespace stop --codespace supreme-spoon-gwxwv6vrx5hwjww

    - name: Wait for 30 seconds
      run: sleep 30

    - name: Restart Codespace
      run: |
        gh codespace start --codespace supreme-spoon-gwxwv6vrx5hwjww
